org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true
org.gradle.parallel=true

mod_id=betteradvancedtooltips
archives_base_name=better-advanced-tooltips
mod_name=Better Advanced Tooltips
maven_group=dev.latvian.mods
mod_author=latvian.dev

mod_version=2603.1.0

neoforge_version=26.3.0.37-beta